### ISSUE TITLE
Fix broken link

### ISSUE THREAD

**Issue by fruwe** [mineiros-io/vscode-terramate#20]
The link to documentation for newbies is broken.

https://github.com/mineiros-io/vscode-terramate/blob/ac2265b0a94d74a84c55e2214d7814db55ad2105/README.md?plain=1#L9

**Comment by soerenmartius** [comment]
thank you! We will fix this shortly!

**Comment by soerenmartius** [comment]
Hi @fruwe,

I just double checked and the link seems to be working again. Maybe this was a temporary outage on medium?

Cheers

**Comment by fruwe** [comment]
@soerenmartius Thank you for checking. I see, *this* link is indeed working.

Maybe publishing a new version of the extension would fix the problem. The link in the README of mineiros.terramate version 0.0.4 (most recent version in vscode) is broken, it points to https://blog.mineiros.io/introducing-terramate-an-orchestrator-and-code-generator-for-terraform-5e538c9ee055

(Btw, the repository's most recent version is still 0.0.3)

**Comment by soerenmartius** [comment]
@fruwe makes total sense - we're on it and will also soon move the extension to our _new_ organization https://github.com/terramate-io

**Comment by fruwe** [comment]
Thanks!!
